name: update bing today image
on:
  schedule:
    - cron: '00 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: 设置 node 运行环境
      - uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: 安装依赖包
        run: pnpm install

      - name: 运行主程序
        run: pnpm index

      - name: 提交变更到 git 本地仓库
        run: |
          git config --local user.email "answer-3@qq.com"
          git config --local user.name "answer-3"
          git pull
          git add docs/*
          git commit -m "update by github actions"

      - name: 推送到 github 远程仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main

          # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build

        # 查看 workflow 的文档来获取更多信息
        # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}